kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tp-elk
nodes:
- role: control-plane
  # Port 30000 : application HTTP (coffee-app)
  # Port 30001 : Kibana
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
